Internship.destroy_all
  Internship.create!(
    title: Faker::Job.title,
    salary: Faker::Number.number(4),
    internship_rating_id: Faker::Number.number(2),
    working_hours: Faker::Number.number(2),
    living_costs: Faker::Number.number(3),
    company_id: Faker::Number.number(3),
    student_id: Faker::Number.number(3),
    semester_id: Faker::Number.number(1),
    start_date: Faker::Date.backward(14),
    end_date: Faker::Date.forward(3),
    operational_area: Faker::Job.field,
    tasks: Faker::ChuckNorris.fact,
    orientation_id: Faker::Number.number(2),
    supervisor_name: Faker::Name.name,
    supervisor_email: Faker::Internet.email,
    registration_state_id: Faker::Number.number(2),
    contract_state_id: Faker::Number.number(1),
    report_state_id: Faker::Number.number(1),
    certificate_state_id: Faker::Number.number(1),
    payment_state_id: Faker::Number.number(1),
    internship_state_id: Faker::Number.number(1),
    comment: Faker::ChuckNorris.fact,
    reading_prof_id: Faker::Number.number(1),
    certificate_to_prof: Faker::Date.backward(5),
    certificate_signed_by_prof: Faker::Date.backward(5),
    certificate_signed_by_internship_officer: Faker::Date.backward(5)
  )